## install packages
FROM node:20.12.0-alpine3.19 AS dependency

WORKDIR /usr/src/app

COPY --chown=node:node . /usr/src/app/

RUN npm ci

## build files
FROM node:20.12.0-alpine3.19 AS build

ENV NODE_ENV production
WORKDIR /usr/src/app

COPY --chown=node:node --from=dependency /usr/src/app/node_modules /usr/src/app/node_modules
COPY --chown=node:node . /usr/src/app/

RUN npm run build
RUN npm prune --production

## execute
FROM node:20.12.0-alpine3.19

ENV NODE_ENV production
WORKDIR /usr/src/app
USER node

COPY --chown=node:node --from=build /usr/src/app/node_modules /usr/src/app/node_modules
COPY --chown=node:node --from=build /usr/src/app/dist /usr/src/app/dist
COPY --chown=node:node . /usr/src/app/

CMD ["node", "dist/main"]
