name: Deploy hosting

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Build
        run: cd client && npm ci && VITE_SERVER_URL=${{ secrets.SERVER_URL }} npm run build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAPSTONE_DESIGN_TEAM6_APP }}
          entryPoint: ./client
          channelId: live
