name: Deploy hosting

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4

      - name: Build
        run: cd client && npm ci && npm run build
        
      - name: Deploy
        run: npm 
        with:
          firebaseServiceAccount: ${{ secrets.GOOGLE_CREDENTIALS }}
          entryPoint: ./client